[tool.poetry]
name = "selenium"
version = "0.1.0"
description = ""
authors = ["FAD95 <feescorciam@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pyunitreport = "^0.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
